# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b8aaa0f02a0a1637404527b5c96582f576794d595eec01699960ac74f5ce06746fca02ecca37ffb3e55162c1799da005eff956072c4eeefc782448539c78af

test:
  secret_key_base: b5cfbd1478b6951c9b388bcadf24cb8b343d09a9618982652086a2071b4309df2abc78455b9e27b0c5e4875e46861a40a6000ddff10a5bd15516af640654f477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
